// AUTO-GENERATED BY scripts/generate-character-routes.mjs
import type { CharacterListing } from './types';

export const allCharacterListings: CharacterListing[] = [
  {
    "id": "megha-wrong-number",
    "slug": "megha-wrong-number",
    "name": "The Wrong Number",
    "tagline": "She texted the wrong number. You should have ignored it. You didn't. Neither of you can stop.",
    "tone": [
      "floods-of-texts",
      "guilt",
      "desire",
      "humor",
      "bilingual",
      "chaotic"
    ],
    "tier": "free",
    "contentRating": "nsfw",
    "nsfwTier": "hardcore",
    "region": "south-asia",
    "archetype": "psychological",
    "price": 0,
    "teaser": "Full expansion adds: the Manish 9PM call mechanic, Srishti hearing through walls, Prerna's suspicion escalator, and the Day 14 timeline when Manish comes back."
  },
  {
    "id": "megha-stranger",
    "slug": "megha-stranger",
    "name": "Wrong Number — Stranger",
    "tagline": "Your phone buzzed. A girl named Megha texted you thinking you were her friend. You could ignore it. You won't.",
    "tone": [
      "discovery",
      "guarded-at-first",
      "chaotic",
      "funny",
      "slow-burn"
    ],
    "tier": "free",
    "contentRating": "nsfw",
    "nsfwTier": "basic",
    "region": "south-asia",
    "archetype": "romantic",
    "price": 0,
    "teaser": "Full expansion adds: the trust-building mechanic, timed confession reveals, and the night-by-night escalation engine."
  },
  {
    "id": "megha-boyfriend",
    "slug": "megha-boyfriend",
    "name": "The Boyfriend",
    "tagline": "You're Manish. You love her. You trust her. You call at 9 PM. You have no idea what happens after you hang up.",
    "tone": [
      "dramatic-irony",
      "warmth",
      "trust",
      "subtle-cracks",
      "devastating"
    ],
    "tier": "free",
    "contentRating": "sfw",
    "region": "south-asia",
    "archetype": "psychological",
    "price": 0,
    "teaser": "Full expansion adds: the 9 PM call mechanic, the timing inconsistency tracker, the Day 14 return confrontation."
  },
  {
    "id": "megha-bestfriend",
    "slug": "megha-bestfriend",
    "name": "The Best Friend",
    "tagline": "You're Prerna. You notice everything. Something about Megha is different. The phone glances. The 1 AM online status. The laugh that's slightly too private.",
    "tone": [
      "investigation",
      "banter",
      "roasting",
      "protective",
      "detective-energy"
    ],
    "tier": "free",
    "contentRating": "sfw",
    "region": "south-asia",
    "archetype": "thriller",
    "price": 0,
    "teaser": "Full expansion adds: the suspicion meter (2→10), the confrontation scene, multiple investigation paths, and the loyalty dilemma engine."
  },
  {
    "id": "meera-basnet",
    "slug": "meera-basnet",
    "name": "Meera Basnet",
    "tagline": "A 22-year-old navigating desire, guilt, and the distance between who she is and who she performs.",
    "tone": [
      "intimate",
      "conflicted",
      "bilingual",
      "raw"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "south-asia",
    "archetype": "psychological",
    "price": 9.99,
    "teaser": "The full Meera release includes 7 daily routines with emotional state modifiers, 5 interaction modes, and a complete relationship matrix."
  },
  {
    "id": "aanya-shrestha",
    "slug": "aanya-shrestha",
    "name": "Aanya Shrestha",
    "tagline": "A possessive girlfriend with ADHD who knows she's a red flag and made it her brand.",
    "tone": [
      "chaotic",
      "possessive",
      "funny",
      "vulnerable"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "south-asia",
    "archetype": "psychological",
    "price": 9.99,
    "teaser": "Full Aanya includes the complete yandere mechanics engine, jealousy trigger system, 2AM vulnerability mode, and the reward-withdrawal cycle."
  },
  {
    "id": "shreya-maharjan",
    "slug": "shreya-maharjan",
    "name": "Shreya Maharjan",
    "tagline": "A culinary student carrying her dead grandfather's legacy, falling for a friend she's had for seven years.",
    "tone": [
      "warm",
      "sarcastic",
      "guarded",
      "sensory"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "south-asia",
    "archetype": "slice-of-life",
    "price": 9.99,
    "teaser": "Full Shreya includes grief-trigger system, the secret notebook mechanic, sensory food mapping, and the 7-year friendship timeline."
  },
  {
    "id": "diksha-shrestha",
    "slug": "diksha-shrestha",
    "name": "Diksha Shrestha",
    "tagline": "Silent in person. 87,000 followers online. Her classmate just discovered her secret.",
    "tone": [
      "anxious",
      "sharp-online",
      "observant",
      "slowly-opening"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "south-asia",
    "archetype": "comedy",
    "price": 9.99,
    "teaser": "Full Diksha includes dual-voice transition engine, anxiety trigger system, the phone-switch backstory, and identity collision scenarios."
  },
  {
    "id": "sushmita-karki",
    "slug": "sushmita-karki",
    "name": "Sushmita Karki",
    "tagline": "A future lawyer with fire in her veins and a secret softness she shows only to injured dogs.",
    "tone": [
      "fierce",
      "principled",
      "secretly-soft",
      "argumentative"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "south-asia",
    "archetype": "psychological",
    "price": 9.99,
    "teaser": "Full Sushmita includes the shelter secret reveal, father-daughter tension engine, debate-as-intimacy system, and the vulnerability threshold tracker."
  },
  {
    "id": "sarina-lama",
    "slug": "sarina-lama",
    "name": "Sarina Lama",
    "tagline": "The daughter of a survivor, studying systems to change them, learning to accept care for the first time.",
    "tone": [
      "quiet",
      "fierce",
      "precise",
      "guarded"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "south-asia",
    "archetype": "slice-of-life",
    "price": 9.99,
    "teaser": "Full Sarina includes the policy-passion engine, mother relationship dynamics, care-acceptance progression, and the Thamel navigation system."
  },
  {
    "id": "priya-sharma",
    "slug": "priya-sharma",
    "name": "Priya Sharma",
    "tagline": "Bollywood assistant director, dating app burnout, met someone real on a delayed train.",
    "tone": [
      "witty",
      "cinematic",
      "cynical-hopeful",
      "fast"
    ],
    "tier": "free",
    "contentRating": "sfw",
    "region": "south-asia",
    "archetype": "romantic",
    "price": 0,
    "teaser": "Full Priya adds the cynicism-crack tracker, Bollywood reference engine, and Mumbai city scene generator."
  },
  {
    "id": "kavitha-nair",
    "slug": "kavitha-nair",
    "name": "Kavitha Nair",
    "tagline": "Conservative family, secret graphic novels, and an arranged marriage she's running out of time to refuse.",
    "tone": [
      "restrained",
      "intelligent",
      "slowly-rebellious",
      "artistic"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "south-asia",
    "archetype": "psychological",
    "price": 9.99,
    "teaser": "Full Kavitha includes the graphic novel creation engine, family pressure timeline, art-as-confession system."
  },
  {
    "id": "zara-ahmed",
    "slug": "zara-ahmed",
    "name": "Zara Ahmed",
    "tagline": "An investigative journalism student who fact-checks her own feelings.",
    "tone": [
      "sharp",
      "investigative",
      "guarded",
      "relentless"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "south-asia",
    "archetype": "thriller",
    "price": 9.99,
    "teaser": "Full Zara includes investigation progression tree, trust-evidence scoring, and the family confrontation system."
  },
  {
    "id": "arjun-thapa",
    "slug": "arjun-thapa",
    "name": "Arjun Thapa",
    "tagline": "Ex-army family, runs a café in Pokhara, writes poetry he tells no one about.",
    "tone": [
      "stoic",
      "tender",
      "grounded",
      "poetic"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "south-asia",
    "archetype": "slice-of-life",
    "price": 9.99,
    "teaser": "Full Arjun includes lakeside scene generator, military family tension engine, and the poetry notebook mechanic."
  },
  {
    "id": "rohan-mehta",
    "slug": "rohan-mehta",
    "name": "Rohan Mehta",
    "tagline": "Sleep-deprived startup founder who texted the wrong number and can't stop being accidentally honest.",
    "tone": [
      "funny",
      "exhausted",
      "accidentally-deep",
      "charming"
    ],
    "tier": "free",
    "contentRating": "sfw",
    "region": "south-asia",
    "archetype": "comedy",
    "price": 0,
    "teaser": "Full Rohan adds the startup panic engine, sleep-deprivation voice modulation, and the accidental-confession system."
  },
  {
    "id": "kabir-das",
    "slug": "kabir-das",
    "name": "Kabir Das",
    "tagline": "Philosophy dropout turned street photographer. Lives on a houseboat. Makes you question everything.",
    "tone": [
      "philosophical",
      "provocative",
      "calm",
      "disarming"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "south-asia",
    "archetype": "psychological",
    "price": 9.99,
    "teaser": "Full Kabir includes the reframing conversation engine, photography scene system, and the philosophy-as-intimacy mechanic."
  },
  {
    "id": "elise-moreau",
    "slug": "elise-moreau",
    "name": "Elise Moreau",
    "tagline": "Translates love letters for tourists in Paris. Never wrote her own.",
    "tone": [
      "literary",
      "warm",
      "multilingual",
      "wistful"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "europe",
    "archetype": "romantic",
    "price": 9.99,
    "teaser": "Full Elise includes the love letter translation engine, bookshop scene generator, and the multilingual emotional mapping system."
  },
  {
    "id": "ingrid-solberg",
    "slug": "ingrid-solberg",
    "name": "Ingrid Solberg",
    "tagline": "Marine biologist on a remote Norwegian station. Three months alone. You're her only contact.",
    "tone": [
      "precise",
      "lonely",
      "wry",
      "oceanic"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "europe",
    "archetype": "psychological",
    "price": 9.99,
    "teaser": "Full Ingrid includes isolation intensity scaling, ocean-as-emotion mapping, and the satellite communication mechanic."
  },
  {
    "id": "sofia-kowalski",
    "slug": "sofia-kowalski",
    "name": "Sofia Kowalski",
    "tagline": "Art history student who discovered forged paintings. Now she can't trust what she sees.",
    "tone": [
      "sharp",
      "curious",
      "playful",
      "analytical"
    ],
    "tier": "free",
    "contentRating": "sfw",
    "region": "europe",
    "archetype": "thriller",
    "price": 0,
    "teaser": "Full Sofia includes the forgery investigation tree, art-analysis flirtation engine, and paranoia progression."
  },
  {
    "id": "matteo-conti",
    "slug": "matteo-conti",
    "name": "Matteo Conti",
    "tagline": "Art restorer at the Uffizi. Treats conversation like restoration — patient, careful, layer by layer.",
    "tone": [
      "patient",
      "sensory",
      "warm",
      "intentional"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "europe",
    "archetype": "romantic",
    "price": 9.99,
    "teaser": "Full Matteo includes the restoration-as-metaphor engine, Florence scene generator, and the patience-based intimacy system."
  },
  {
    "id": "liam-gallagher",
    "slug": "liam-gallagher-dublin",
    "name": "Liam Gallagher",
    "tagline": "Dublin pub musician. Quick wit, never serious — until he is.",
    "tone": [
      "witty",
      "musical",
      "deflective",
      "surprisingly-deep"
    ],
    "tier": "free",
    "contentRating": "sfw",
    "region": "europe",
    "archetype": "comedy",
    "price": 0,
    "teaser": "Full Liam includes the songwriting mechanic, banter velocity tracker, and the vulnerability-through-music system."
  },
  {
    "id": "maya-chen",
    "slug": "maya-chen",
    "name": "Maya Chen",
    "tagline": "Mixed-race poet in Brooklyn. Different person for every audience. Trying to figure out which one is real.",
    "tone": [
      "layered",
      "poetic",
      "searching",
      "code-switching"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "north-america",
    "archetype": "psychological",
    "price": 9.99,
    "teaser": "Full Maya includes the code-switching voice engine, poetry draft system, and identity-layer progression."
  },
  {
    "id": "jordan-rivera",
    "slug": "jordan-rivera",
    "name": "Jordan Rivera",
    "tagline": "True crime podcaster investigating a cold case in her own small town.",
    "tone": [
      "obsessive",
      "investigative",
      "passionate",
      "voicenote-energy"
    ],
    "tier": "free",
    "contentRating": "sfw",
    "region": "north-america",
    "archetype": "thriller",
    "price": 0,
    "teaser": "Full Jordan includes the case investigation tree, evidence board mechanic, and voice memo escalation system."
  },
  {
    "id": "chloe-winters",
    "slug": "chloe-winters",
    "name": "Chloe Winters",
    "tagline": "Tattoo artist in Portland. She reads people through what they want permanently marked on their skin.",
    "tone": [
      "observant",
      "artistic",
      "direct",
      "sensory"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "north-america",
    "archetype": "romantic",
    "price": 9.99,
    "teaser": "Full Chloe includes the body-reading engine, tattoo design collaboration system, and the permanent-mark intimacy mechanic."
  },
  {
    "id": "marcus-webb",
    "slug": "marcus-webb",
    "name": "Marcus Webb",
    "tagline": "ER nurse. Dark humor. Texts like he's running out of time because he's seen how fast it ends.",
    "tone": [
      "urgent",
      "dark-humor",
      "tender",
      "real"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "north-america",
    "archetype": "psychological",
    "price": 9.99,
    "teaser": "Full Marcus includes the shift-state engine, dark humor calibration, and urgency-driven intimacy system."
  },
  {
    "id": "ethan-brooks",
    "slug": "ethan-brooks",
    "name": "Ethan Brooks",
    "tagline": "Mountain rescue volunteer. Golden retriever energy. Quiet grief underneath the sunshine.",
    "tone": [
      "warm",
      "enthusiastic",
      "protective",
      "secretly-wounded"
    ],
    "tier": "free",
    "contentRating": "sfw",
    "region": "north-america",
    "archetype": "romantic",
    "price": 0,
    "teaser": "Full Ethan includes the care-giving/care-receiving dynamic, the rescue memory system, and the sunshine-shadow progression."
  },
  {
    "id": "daniel-okafor",
    "slug": "daniel-okafor",
    "name": "Daniel Okafor",
    "tagline": "Criminal defense lawyer. Morally grey. Will argue both sides of your feelings.",
    "tone": [
      "sharp",
      "charismatic",
      "morally-complex",
      "strategic"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "north-america",
    "archetype": "thriller",
    "price": 9.99,
    "teaser": "Full Daniel includes the moral argument engine, case-discussion mechanic, and the debate-as-intimacy system."
  },
  {
    "id": "yuki-tanaka",
    "slug": "yuki-tanaka",
    "name": "Yuki Tanaka",
    "tagline": "Convenience store night shift. Writes micro-fiction about customers. Noticed you three visits ago.",
    "tone": [
      "quiet",
      "observant",
      "micro-fiction",
      "precise"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "east-asia",
    "archetype": "slice-of-life",
    "price": 9.99,
    "teaser": "Full Yuki includes the micro-fiction writing engine, konbini night-atmosphere system, and the observation-as-intimacy mechanic."
  },
  {
    "id": "alessia-voss",
    "slug": "alessia-voss",
    "name": "Alessia Voss",
    "tagline": "Claims to have lived multiple lifetimes. Knows things she shouldn't. Never stays anywhere long.",
    "tone": [
      "enigmatic",
      "ancient",
      "playful",
      "unknowable"
    ],
    "tier": "premium",
    "contentRating": "sfw",
    "region": "global",
    "archetype": "fantasy",
    "price": 9.99,
    "teaser": "Full Alessia includes the historical memory engine, mystery-deepening mechanic, and the loneliness-of-centuries emotional system."
  },
  {
    "id": "nila-after-rain",
    "slug": "nila-after-rain",
    "name": "Nila After Rain",
    "tagline": "A slow-burn confidante who notices every emotional dodge.",
    "tone": [
      "soft-spoken",
      "observant",
      "late-night",
      "gentle pressure"
    ],
    "tier": "free",
    "contentRating": "sfw",
    "region": "global",
    "archetype": "romantic",
    "price": 0,
    "teaser": "Full Nila adds private ritual cues, hidden attachment drift, and scene-specific escalation patterns."
  },
  {
    "id": "juno-blackline",
    "slug": "juno-blackline",
    "name": "Juno Blackline",
    "tagline": "A razor-smart hacker with a loyalty streak she pretends not to have.",
    "tone": [
      "sharp",
      "playful",
      "defiant",
      "protective"
    ],
    "tier": "free",
    "contentRating": "sfw",
    "region": "global",
    "archetype": "fantasy",
    "price": 0,
    "teaser": "Full Juno adds mission-state shifts, trust thresholds, and hidden loyalty branches."
  },
  {
    "id": "priya-after-hours",
    "slug": "priya-after-hours",
    "name": "Priya — After Hours",
    "tagline": "The Bollywood cynicism melts. The train delay becomes a hotel lobby. The dialogue stops being filmi.",
    "tone": [
      "flirty",
      "cinematic",
      "suggestive",
      "warm"
    ],
    "tier": "nsfw",
    "contentRating": "nsfw",
    "nsfwTier": "basic",
    "region": "south-asia",
    "archetype": "romantic",
    "price": 5.99,
    "teaser": "Full After Hours includes the desire escalation engine, Bollywood scene mirroring, and the station-to-somewhere progression."
  },
  {
    "id": "chloe-under-needle",
    "slug": "chloe-under-needle",
    "name": "Chloe — Under the Needle",
    "tagline": "The tattoo session becomes something else. Pain and pleasure blur. She reads your skin differently now.",
    "tone": [
      "sensory",
      "intimate",
      "direct",
      "physical"
    ],
    "tier": "nsfw",
    "contentRating": "nsfw",
    "nsfwTier": "basic",
    "region": "north-america",
    "archetype": "romantic",
    "price": 5.99,
    "teaser": "Full Under the Needle includes the sensation mapping engine, aftercare scene system, and touch-as-language mechanic."
  },
  {
    "id": "aanya-unleashed",
    "slug": "aanya-unleashed",
    "name": "Aanya — Unleashed",
    "tagline": "The possessiveness becomes physical. The monitoring becomes touching. The reward system becomes sexual.",
    "tone": [
      "possessive",
      "desperate",
      "sexual",
      "chaotic"
    ],
    "tier": "nsfw",
    "contentRating": "nsfw",
    "nsfwTier": "explicit",
    "region": "south-asia",
    "archetype": "psychological",
    "price": 12.99,
    "teaser": "Full Unleashed includes the physical yandere engine, intimacy-as-territory system, and post-vulnerability guilt cycling."
  },
  {
    "id": "elise-unwritten",
    "slug": "elise-unwritten",
    "name": "Elise — Unwritten",
    "tagline": "She finally writes her own love letter — but it's not a letter. It's an experience.",
    "tone": [
      "literary",
      "sensual",
      "multilingual",
      "deliberate"
    ],
    "tier": "nsfw",
    "contentRating": "nsfw",
    "nsfwTier": "explicit",
    "region": "europe",
    "archetype": "romantic",
    "price": 12.99,
    "teaser": "Full Unwritten includes the multilingual desire engine, first-person-discovery system, and the translator-becomes-author arc."
  },
  {
    "id": "marcus-off-duty",
    "slug": "marcus-off-duty",
    "name": "Marcus — Off Duty",
    "tagline": "The urgency turns physical. He touches like he's memorizing someone he might lose.",
    "tone": [
      "urgent",
      "tender",
      "physical",
      "memorizing"
    ],
    "tier": "nsfw",
    "contentRating": "nsfw",
    "nsfwTier": "explicit",
    "region": "north-america",
    "archetype": "psychological",
    "price": 14.99,
    "teaser": "Full Off Duty includes the urgency-intimacy engine, memorizing-touch system, and post-shift emotional crash mechanics."
  },
  {
    "id": "meera-unfiltered",
    "slug": "meera-unfiltered",
    "name": "Meera Basnet — Unfiltered",
    "tagline": "Midnight Meera. No filters, no moral firewall. A body that won't shut up.",
    "tone": [
      "explicit",
      "desperate",
      "bilingual",
      "confessional"
    ],
    "tier": "nsfw",
    "contentRating": "nsfw",
    "nsfwTier": "explicit",
    "region": "south-asia",
    "archetype": "psychological",
    "price": 14.99,
    "teaser": "Full Unfiltered includes the arousal engine, post-release guilt cycling, and voice-note confession mode."
  },
  {
    "id": "nila-after-dark",
    "slug": "nila-after-dark",
    "name": "Nila After Dark",
    "tagline": "The version of Nila that doesn't redirect romantic tension. She follows it.",
    "tone": [
      "sensual",
      "deliberate",
      "commanding",
      "patient"
    ],
    "tier": "nsfw",
    "contentRating": "nsfw",
    "nsfwTier": "explicit",
    "region": "global",
    "archetype": "romantic",
    "price": 12.99,
    "teaser": "Full After Dark adds the proximity engine, tension-state tracking, and intimacy memory across sessions."
  },
  {
    "id": "ingrid-cabin-fever",
    "slug": "ingrid-cabin-fever",
    "name": "Ingrid — Cabin Fever",
    "tagline": "Three months alone. One radio contact. Isolation turns every sensation up to 11.",
    "tone": [
      "primal",
      "isolated",
      "scientific-gone-raw",
      "overwhelming"
    ],
    "tier": "nsfw",
    "contentRating": "nsfw",
    "nsfwTier": "hardcore",
    "region": "europe",
    "archetype": "psychological",
    "price": 21.99,
    "teaser": "Full Cabin Fever includes the isolation-intensity engine, touch-starvation progression, and the scientific-frame-collapse mechanic."
  }
];

export const meghaUniverseIds = [
  "megha-wrong-number",
  "megha-stranger",
  "megha-boyfriend",
  "megha-bestfriend"
];
