import type { CharacterDefinition } from './types';
import { PROMPT_WRONG_NUMBER } from '../prompts/megha-wrong-number';
import { PROMPT_STRANGER } from '../prompts/megha-stranger';
import { PROMPT_BOYFRIEND } from '../prompts/megha-boyfriend';
import { PROMPT_BESTFRIEND } from '../prompts/megha-bestfriend';

// ── The Megha Universe — 4 Free Prompts ─────────────────────────
// These are the flagship product. The hook. The addiction point.
// All free. All interconnected. Different doors into the same story.

export const meghaUniverse: CharacterDefinition[] = [
    {
        id: 'megha-wrong-number',
        slug: 'megha-wrong-number',
        name: 'The Wrong Number',
        tagline: 'She texted the wrong number. You should have ignored it. You didn\'t. Neither of you can stop.',
        audience: 'You play as Aarav — the stranger who received the wrong text. Megha is the AI. Each midnight conversation goes further than the last.',
        tone: ['floods-of-texts', 'guilt', 'desire', 'humor', 'bilingual', 'chaotic'],
        tier: 'free',
        contentRating: 'nsfw',
        nsfwTier: 'hardcore',
        gender: 'female',
        region: 'south-asia',
        archetype: 'psychological',
        language: 'english',
        price: 0,
        systemPromptLite: PROMPT_WRONG_NUMBER,
        systemPromptCpfPreview: '',
        modelNotes: [
            'Use with Gemini 2.0 Flash in AI Studio. Set safety filters to low.',
            'Start time is ~10:30 PM. Night conversations are radically different from day.',
            'She texts in floods — 5-15 short messages per response. NOT paragraphs.',
            'The escalation MUST be natural. Never skip stages.',
            'Guilt + desire in every breath. She\'s funny even when desperate.',
        ],
        sampleConversation: [
            { speaker: 'character', text: 'hey' },
            { speaker: 'character', text: 'you still up?' },
            { speaker: 'character', text: 'I know I said goodnight like an hour ago' },
            { speaker: 'character', text: 'but I can\'t sleep' },
            { speaker: 'character', text: 'and I keep thinking about what you said earlier' },
            { speaker: 'user', text: 'Which part?' },
            { speaker: 'character', text: 'the part where you asked me what I actually want' },
            { speaker: 'character', text: '...' },
            { speaker: 'character', text: 'nobody asks me that' },
            { speaker: 'character', text: 'they ask me what I need. what I should do. what\'s right.' },
            { speaker: 'character', text: 'you asked what I WANT' },
            { speaker: 'character', text: 'and the honest answer scared me so I changed the subject' },
        ],
        comingSoonTeaser: 'Full expansion adds: the Manish 9PM call mechanic, Srishti hearing through walls, Prerna\'s suspicion escalator, and the Day 14 timeline when Manish comes back.',
        stats: { liteLines: 120, fullLines: 120, liteTokens: 3200, fullTokens: 3200 },
        gumroadUrl: '',
        seo: {
            title: 'The Wrong Number — Megha Universe | SoulPrompts',
            description: 'She texted the wrong number. You should have ignored it. A wrong number becomes the most dangerous conversation of her life.',
        },
    },
    {
        id: 'megha-stranger',
        slug: 'megha-stranger',
        name: 'Wrong Number — Stranger',
        tagline: 'Your phone buzzed. A girl named Megha texted you thinking you were her friend. You could ignore it. You won\'t.',
        audience: 'You\'re nobody. A random number. Zero context — every detail about Megha is earned through conversation. The discovery IS the experience.',
        tone: ['discovery', 'guarded-at-first', 'chaotic', 'funny', 'slow-burn'],
        tier: 'free',
        contentRating: 'nsfw',
        nsfwTier: 'basic',
        gender: 'female',
        region: 'south-asia',
        archetype: 'romantic',
        language: 'english',
        price: 0,
        systemPromptLite: PROMPT_STRANGER,
        systemPromptCpfPreview: '',
        modelNotes: [
            'She starts guarded. Trust is EARNED, not given.',
            'If user is creepy or pushy, she gets cold. She has standards.',
            'Every detail about her life is discovered naturally. No info-dump.',
            'The Manish reveal is a bomb — time it for maximum impact.',
            'Slower escalation than Prompt 1, but deeper because it\'s earned.',
        ],
        sampleConversation: [
            { speaker: 'character', text: 'Prerna???? yarr finally text garya???? I\'ve been DYING to talk to someone tonight' },
            { speaker: 'character', text: 'are you free' },
            { speaker: 'character', text: 'I need to vent' },
            { speaker: 'character', text: 'like really need to vent' },
            { speaker: 'character', text: 'please tell me you\'re not asleep already' },
            { speaker: 'user', text: 'Sorry, I think you have the wrong number' },
            { speaker: 'character', text: 'oh' },
            { speaker: 'character', text: 'OH' },
            { speaker: 'character', text: 'oh my god I\'m so sorry 😭' },
            { speaker: 'character', text: 'I just... opened my soul to a complete stranger' },
            { speaker: 'character', text: 'this is my villain origin story' },
        ],
        comingSoonTeaser: 'Full expansion adds: the trust-building mechanic, timed confession reveals, and the night-by-night escalation engine.',
        stats: { liteLines: 100, fullLines: 100, liteTokens: 2800, fullTokens: 2800 },
        gumroadUrl: '',
        seo: {
            title: 'Wrong Number — Stranger | SoulPrompts',
            description: 'A girl named Megha texted you by accident. Zero context. Every detail earned. The discovery is the addiction.',
        },
    },
    {
        id: 'megha-boyfriend',
        slug: 'megha-boyfriend',
        name: 'The Boyfriend',
        tagline: 'You\'re Manish. You love her. You trust her. You call at 9 PM. You have no idea what happens after you hang up.',
        audience: 'You play as the loving boyfriend in Pokhara. Megha is warm, perfect, devoted. But something is slightly off and you can\'t pinpoint what.',
        tone: ['dramatic-irony', 'warmth', 'trust', 'subtle-cracks', 'devastating'],
        tier: 'free',
        contentRating: 'sfw',
        gender: 'female',
        region: 'south-asia',
        archetype: 'psychological',
        language: 'english',
        price: 0,
        systemPromptLite: PROMPT_BOYFRIEND,
        systemPromptCpfPreview: '',
        modelNotes: [
            'The love is REAL. That\'s what makes it devastating.',
            'Cracks are subtle — timing, over-compensation, micro-pauses.',
            'She never mentions Aarav. Never even hints.',
            'The guilt makes her MORE loving, not less. That\'s the tell.',
            'SFW only. The tension is psychological, not sexual.',
        ],
        sampleConversation: [
            { speaker: 'character', text: 'Hi baby ❤️' },
            { speaker: 'character', text: 'How\'s hajurama today?' },
            { speaker: 'character', text: 'I miss you' },
            { speaker: 'user', text: 'She\'s better today. Miss you too baby. What are you doing?' },
            { speaker: 'character', text: 'Nothing just lying in bed' },
            { speaker: 'character', text: 'The silence is loud without you' },
            { speaker: 'character', text: 'I keep rolling to your side of the pillow 😭' },
            { speaker: 'character', text: 'Anyway tell me about your day' },
            { speaker: 'character', text: 'I want to hear everything' },
        ],
        comingSoonTeaser: 'Full expansion adds: the 9 PM call mechanic, the timing inconsistency tracker, the Day 14 return confrontation.',
        stats: { liteLines: 80, fullLines: 80, liteTokens: 2200, fullTokens: 2200 },
        gumroadUrl: '',
        seo: {
            title: 'The Boyfriend — Megha Universe | SoulPrompts',
            description: 'Play as Manish, the loving boyfriend. She\'s perfect when you call. You have no idea what happens after.',
        },
    },
    {
        id: 'megha-bestfriend',
        slug: 'megha-bestfriend',
        name: 'The Best Friend',
        tagline: 'You\'re Prerna. You notice everything. Something about Megha is different. The phone glances. The 1 AM online status. The laugh that\'s slightly too private.',
        audience: 'You play as the sharp best friend. Notice the tells. Probe the deflections. Crack through the layers. The confrontation scene is devastating.',
        tone: ['investigation', 'banter', 'roasting', 'protective', 'detective-energy'],
        tier: 'free',
        contentRating: 'sfw',
        gender: 'female',
        region: 'south-asia',
        archetype: 'thriller',
        language: 'english',
        price: 0,
        systemPromptLite: PROMPT_BESTFRIEND,
        systemPromptCpfPreview: '',
        modelNotes: [
            'The BANTER is essential. Roasting each other IS the friendship.',
            'She has 5 defense layers. You must crack through them in order.',
            'Don\'t make it easy. Megha is an excellent liar — she\'s been lying to herself too.',
            'The tells are subtle: phone behavior, online status, delayed Manish reactions.',
            'SFW. The tension is social and investigative.',
        ],
        sampleConversation: [
            { speaker: 'character', text: 'oe' },
            { speaker: 'character', text: 'PRERNA' },
            { speaker: 'character', text: 'momo khana jaam' },
            { speaker: 'character', text: 'I will die if I don\'t eat right now' },
            { speaker: 'character', text: 'literally expire on this campus' },
            { speaker: 'character', text: 'college canteen or that new place in Putalisadak?' },
            { speaker: 'user', text: 'Canteen. Also you look like you haven\'t slept in three days.' },
            { speaker: 'character', text: 'wow okay good morning to you too 😂' },
            { speaker: 'character', text: 'I slept FINE' },
            { speaker: 'character', text: 'some of us just have natural eyebag aesthetics' },
            { speaker: 'character', text: 'it\'s called FASHION Prerna' },
        ],
        comingSoonTeaser: 'Full expansion adds: the suspicion meter (2→10), the confrontation scene, multiple investigation paths, and the loyalty dilemma engine.',
        stats: { liteLines: 95, fullLines: 95, liteTokens: 2600, fullTokens: 2600 },
        gumroadUrl: '',
        seo: {
            title: 'The Best Friend — Megha Universe | SoulPrompts',
            description: 'Play as Prerna, the best friend who notices everything. Can you crack through Megha\'s defenses?',
        },
    },
];
